backend:
  name: git-gateway
  branch: dev-astro # Branch to update (optional; defaults to master)
local_backend: true
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "public/images" # The src attribute for uploaded media

collections:
  - label: "Resources"
    name: "resources"
    files:
      - label: "Resources"
        name: "resources"
        file: "src/data/resources.yml"
        fields:
          - label: "Resources"
            name: "resources"
            widget: "object"
            collapsed: false
            create: true
            fields:
              - name: "Web Development"
                label: "Web Development"
                widget: "list"
                fields:
                  - name: "title"
                    label: "Title"
                    widget: "string"
                  - name: "url"
                    label: "URL"
                    widget: "string"
                  - name: "tags"
                    label: "Tags"
                    widget: "string"
                    required: false
                    hint: "Enter tags separated by commas (e.g., 'Astro, Documentation')"
                  - name: "screenshot"
                    label: "Screenshot"
                    widget: "image"
                    required: false

              - name: "Design"
                label: "Design"
                widget: "list"
                fields:
                  - name: "title"
                    label: "Title"
                    widget: "string"
                  - name: "url"
                    label: "URL"
                    widget: "string"
                  - name: "tags"
                    label: "Tags"
                    widget: "string"
                    required: false
                    hint: "Enter tags separated by commas (e.g., 'Design, Portfolio')"
                  - name: "screenshot"
                    label: "Screenshot"
                    widget: "image"
                    required: false

              # Add more categories as needed
              - name: "Tutorials"
                label: "Tutorials"
                widget: "list"
                fields:
                  - name: "title"
                    label: "Title"
                    widget: "string"
                  - name: "url"
                    label: "URL"
                    widget: "string"
                  - name: "tags"
                    label: "Tags"
                    widget: "string"
                    required: false
                    hint: "Enter tags separated by commas (e.g., 'HTML, CSS')"
                  - name: "screenshot"
                    label: "Screenshot"
                    widget: "image"
                    required: false

              - name: "Tools"
                label: "Tools"
                widget: "list"
                fields:
                  - name: "title"
                    label: "Title"
                    widget: "string"
                  - name: "url"
                    label: "URL"
                    widget: "string"
                  - name: "tags"
                    label: "Tags"
                    widget: "string"
                    required: false
                    hint: "Enter tags separated by commas (e.g., 'Productivity')"
                  - name: "screenshot"
                    label: "Screenshot"
                    widget: "image"
                    required: false
